docs: ORPmref.pdf

ORPmref.pdf: ORPmref.tex
	pdflatex ORPmref.tex

clean distclean:
	rm -f ORPmref.aux ORPmref.pdf ORPmref.log

#########################################################################

.depend:
