#
#  $Id: Makefile.dir,v 1.2 2001-09-27 12:02:50 chris Exp $
#

include $(RTEMS_MAKEFILE_PATH)/Makefile.inc

include $(RTEMS_CUSTOM)
include $(RTEMS_ROOT)/make/directory.cfg

SUBDIRS=a b c your-directories-go-here

